[package]
name = "pktool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
pnet = "0.28.0"
pnet_datalink = "0.28.0"
log = "0.4.0"
env_logger = "0.8.4"